services:
  postgres:
    image: postgres:16-alpine
    container_name: learning_platform_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learningplatform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - learning_platform_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: learning_platform_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - learning_platform_network

volumes:
  postgres_data:

networks:
  learning_platform_network:
    driver: bridge